services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: finances
      POSTGRES_PASSWORD: finances
      POSTGRES_DB: finances
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - finances-net

volumes:
  pgdata:

networks:
  finances-net:
    driver: bridge
