// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CategoryExpense struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type CategoryIncome struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type Expense struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	SubcategoryID   int32              `json:"subcategory_id"`
	Value           pgtype.Numeric     `json:"value"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Income struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	CategoryID      int32              `json:"category_id"`
	Value           pgtype.Numeric     `json:"value"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SubcategoryExpense struct {
	ID          int32  `json:"id"`
	CategoryID  int32  `json:"category_id"`
	Description string `json:"description"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
